local:
  J2_FORTUNE_REPLICAS_MIN: 1
  J2_FORTUNE_REPLICAS_MAX: 1
  J2_READER_REPLICAS: 1

test:
  J2_FORTUNE_REPLICAS_MIN: 2
  J2_FORTUNE_REPLICAS_MAX: 3
  J2_READER_REPLICAS: 2

live:
  J2_FORTUNE_REPLICAS_MIN: 4
  J2_FORTUNE_REPLICAS_MAX: 18
  J2_READER_REPLICAS: 3
