apiVersion: v1
kind: Route
metadata:
  name: reader
  namespace: fortune
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: reader
---
apiVersion: v1
kind: Route
metadata:
  name: reader-info
  namespace: fortune
spec:
  path: /info.php
  port:
    targetPort: http
  to:
    kind: Service
    name: reader
