/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Current Database: `fortune`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `fortune` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `fortune`;


--
-- Table structure for table `quotes`
--

DROP TABLE IF EXISTS `quotes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `quotes` (
  `body` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `quotes`
--

LOCK TABLES `quotes` WRITE;
/*!40000 ALTER TABLE `quotes` DISABLE KEYS */;
INSERT INTO `quotes` VALUES ('A day for firm decisions!!!!!  Or is it?');
INSERT INTO `quotes` VALUES ('A few hours grace before the madness begins again.');
INSERT INTO `quotes` VALUES ('A gift of a flower will soon be made to you.');
INSERT INTO `quotes` VALUES ('A long-forgotten loved one will appear soon.\n\nBuy the negatives at any price.');
INSERT INTO `quotes` VALUES ('A tall, dark stranger will have more fun than you.');
INSERT INTO `quotes` VALUES ('A visit to a fresh place will bring strange work.');
INSERT INTO `quotes` VALUES ('A visit to a strange place will bring fresh work.');
INSERT INTO `quotes` VALUES ('A vivid and creative mind characterizes you.');
INSERT INTO `quotes` VALUES ('Abandon the search for Truth; settle for a good fantasy.');
INSERT INTO `quotes` VALUES ('Accent on helpful side of your nature.  Drain the moat.');
INSERT INTO `quotes` VALUES ('Advancement in position.');
INSERT INTO `quotes` VALUES ('After your lover has gone you will still have PEANUT BUTTER!');
INSERT INTO `quotes` VALUES ('Afternoon very favorable for romance.  Try a single person for a change.');
INSERT INTO `quotes` VALUES ('Alimony and bribes will engage a large share of your wealth.');
INSERT INTO `quotes` VALUES ('All the troubles you have will pass away very quickly.');
INSERT INTO `quotes` VALUES ('Among the lucky, you are the chosen one.');
INSERT INTO `quotes` VALUES ('An avocado-tone refrigerator would look good on your resume.');
INSERT INTO `quotes` VALUES ('An exotic journey in downtown Newark is in your future.');
INSERT INTO `quotes` VALUES ('Another good night not to sleep in a eucalyptus tree.');
INSERT INTO `quotes` VALUES ('Are you a turtle?');
INSERT INTO `quotes` VALUES ('Are you ever going to do the dishes?  Or will you change your major to biology?');
INSERT INTO `quotes` VALUES ('Are you making all this up as you go along?');
INSERT INTO `quotes` VALUES ('Are you sure the back door is locked?');
INSERT INTO `quotes` VALUES ('Artistic ventures highlighted.  Rob a museum.');
INSERT INTO `quotes` VALUES ('Avert misunderstanding by calm, poise, and balance.');
INSERT INTO `quotes` VALUES ('Avoid gunfire in the bathroom tonight.');
INSERT INTO `quotes` VALUES ('Avoid reality at all costs.');
INSERT INTO `quotes` VALUES ('Bank error in your favor.  Collect $200.');
INSERT INTO `quotes` VALUES ('Be careful!  Is it classified?');
INSERT INTO `quotes` VALUES ('Be careful!  UGLY strikes 9 out of 10!');
INSERT INTO `quotes` VALUES ('Be cautious in your daily affairs.');
INSERT INTO `quotes` VALUES ('Be cheerful while you are alive.\n		-- Phathotep, 24th Century B.C.');
INSERT INTO `quotes` VALUES ('Be different: conform.');
INSERT INTO `quotes` VALUES ('Be free and open and breezy!  Enjoy!  Things won\'t get any better so\nget used to it.');
INSERT INTO `quotes` VALUES ('Be security conscious -- National defense is at stake.');
INSERT INTO `quotes` VALUES ('Beauty and harmony are as necessary to you as the very breath of life.');
INSERT INTO `quotes` VALUES ('Best of all is never to have been born.  Second best is to die soon.');
INSERT INTO `quotes` VALUES ('Better hope the life-inspector doesn\'t come around while you have your\nlife in such a mess.');
INSERT INTO `quotes` VALUES ('Beware of a dark-haired man with a loud tie.');
INSERT INTO `quotes` VALUES ('Beware of a tall black man with one blond shoe.');
INSERT INTO `quotes` VALUES ('Beware of a tall blond man with one black shoe.');
INSERT INTO `quotes` VALUES ('Beware of Bigfoot!');
INSERT INTO `quotes` VALUES ('Beware of low-flying butterflies.');
INSERT INTO `quotes` VALUES ('Beware the one behind you.');
INSERT INTO `quotes` VALUES ('Blow it out your ear.');
INSERT INTO `quotes` VALUES ('Break into jail and claim police brutality.');
INSERT INTO `quotes` VALUES ('Bridge ahead.  Pay troll.');
INSERT INTO `quotes` VALUES ('Caution: breathing may be hazardous to your health.');
INSERT INTO `quotes` VALUES ('Caution: Keep out of reach of children.');
INSERT INTO `quotes` VALUES ('Celebrate Hannibal Day this year.  Take an elephant to lunch.');
INSERT INTO `quotes` VALUES ('Change your thoughts and you change your world.');
INSERT INTO `quotes` VALUES ('Cheer Up!  Things are getting worse at a slower rate.');
INSERT INTO `quotes` VALUES ('Chess tonight.');
INSERT INTO `quotes` VALUES ('Chicken Little only has to be right once.');
INSERT INTO `quotes` VALUES ('Chicken Little was right.');
INSERT INTO `quotes` VALUES ('Cold hands, no gloves.');
INSERT INTO `quotes` VALUES ('Communicate!  It can\'t make things any worse.');
INSERT INTO `quotes` VALUES ('Courage is your greatest present need.');
INSERT INTO `quotes` VALUES ('Day of inquiry.  You will be subpoenaed.');
INSERT INTO `quotes` VALUES ('Do not overtax your powers.');
INSERT INTO `quotes` VALUES ('Do not sleep in a eucalyptus tree tonight.');
INSERT INTO `quotes` VALUES ('Do nothing unless you must, and when you must act -- hesitate.');
INSERT INTO `quotes` VALUES ('Do something unusual today.  Pay a bill.');
INSERT INTO `quotes` VALUES ('Do what comes naturally.  Seethe and fume and throw a tantrum.');
INSERT INTO `quotes` VALUES ('Domestic happiness and faithful friends.');
INSERT INTO `quotes` VALUES ('Don\'t feed the bats tonight.');
INSERT INTO `quotes` VALUES ('Don\'t get stuck in a closet -- wear yourself out.');
INSERT INTO `quotes` VALUES ('Don\'t get to bragging.');
INSERT INTO `quotes` VALUES ('Don\'t go surfing in South Dakota for a while.');
INSERT INTO `quotes` VALUES ('Don\'t hate yourself in the morning -- sleep till noon.');
INSERT INTO `quotes` VALUES ('Don\'t kiss an elephant on the lips today.');
INSERT INTO `quotes` VALUES ('Don\'t let your mind wander -- it\'s too little to be let out alone.');
INSERT INTO `quotes` VALUES ('Don\'t look back, the lemmings are gaining on you.');
INSERT INTO `quotes` VALUES ('Don\'t look now, but the man in the moon is laughing at you.');
INSERT INTO `quotes` VALUES ('Don\'t look now, but there is a multi-legged creature on your shoulder.');
INSERT INTO `quotes` VALUES ('Don\'t plan any hasty moves.  You\'ll be evicted soon anyway.');
INSERT INTO `quotes` VALUES ('Don\'t read any sky-writing for the next two weeks.');
INSERT INTO `quotes` VALUES ('Don\'t read everything you believe.');
INSERT INTO `quotes` VALUES ('Don\'t relax!  It\'s only your tension that\'s holding you together.');
INSERT INTO `quotes` VALUES ('Don\'t tell any big lies today.  Small ones can be just as effective.');
INSERT INTO `quotes` VALUES ('Don\'t worry so loud, your roommate can\'t think.');
INSERT INTO `quotes` VALUES ('Don\'t Worry, Be Happy.\n		-- Meher Baba');
INSERT INTO `quotes` VALUES ('Don\'t worry.  Life\'s too long.\n		-- Vincent Sardi, Jr.');
INSERT INTO `quotes` VALUES ('Don\'t you feel more like you do now than you did when you came in?');
INSERT INTO `quotes` VALUES ('Don\'t you wish you had more energy... or less ambition?');
INSERT INTO `quotes` VALUES ('Everything that you know is wrong, but you can be straightened out.');
INSERT INTO `quotes` VALUES ('Everything will be just tickety-boo today.');
INSERT INTO `quotes` VALUES ('Excellent day for putting Slinkies on an escalator.');
INSERT INTO `quotes` VALUES ('Excellent day to have a rotten day.');
INSERT INTO `quotes` VALUES ('Excellent time to become a missing person.');
INSERT INTO `quotes` VALUES ('Executive ability is prominent in your make-up.');
INSERT INTO `quotes` VALUES ('Exercise caution in your daily affairs.');
INSERT INTO `quotes` VALUES ('Expect a letter from a friend who will ask a favor of you.');
INSERT INTO `quotes` VALUES ('Expect the worst, it\'s the least you can do.');
INSERT INTO `quotes` VALUES ('Fine day for friends.\nSo-so day for you.');
INSERT INTO `quotes` VALUES ('Fine day to work off excess energy.  Steal something heavy.');
INSERT INTO `quotes` VALUES ('Fortune: You will be attacked next Wednesday at 3:15 p.m. by six samurai\nsword wielding purple fish glued to Harley-Davidson motorcycles.\n\nOh, and have a nice day!\n		-- Bryce Nesbitt \'84');
INSERT INTO `quotes` VALUES ('Future looks spotty.  You will spill soup in late evening.');
INSERT INTO `quotes` VALUES ('Generosity and perfection are your everlasting goals.');
INSERT INTO `quotes` VALUES ('Give him an evasive answer.');
INSERT INTO `quotes` VALUES ('Give thought to your reputation.  Consider changing name and moving to\na new town.');
INSERT INTO `quotes` VALUES ('Give your very best today.  Heaven knows it\'s little enough.');
INSERT INTO `quotes` VALUES ('Go to a movie tonight.  Darkness becomes you.');
INSERT INTO `quotes` VALUES ('Good day for a change of scene.  Repaper the bedroom wall.');
INSERT INTO `quotes` VALUES ('Good day for overcoming obstacles.  Try a steeplechase.');
INSERT INTO `quotes` VALUES ('Good day to deal with people in high places; particularly lonely stewardesses.');
INSERT INTO `quotes` VALUES ('Good day to let down old friends who need help.');
INSERT INTO `quotes` VALUES ('Good news from afar can bring you a welcome visitor.');
INSERT INTO `quotes` VALUES ('Good news.  Ten weeks from Friday will be a pretty good day.');
INSERT INTO `quotes` VALUES ('Good night to spend with family, but avoid arguments with your mate\'s\nnew lover.');
INSERT INTO `quotes` VALUES ('Green light in A.M. for new projects.  Red light in P.M. for traffic tickets.');
INSERT INTO `quotes` VALUES ('Hope that the day after you die is a nice day.');
INSERT INTO `quotes` VALUES ('If you can read this, you\'re too close.');
INSERT INTO `quotes` VALUES ('If you learn one useless thing every day, in a single year you\'ll learn\n365 useless things.');
INSERT INTO `quotes` VALUES ('If you sow your wild oats, hope for a crop failure.');
INSERT INTO `quotes` VALUES ('If you stand on your head, you will get footprints in your hair.');
INSERT INTO `quotes` VALUES ('If you think last Tuesday was a drag, wait till you see what happens tomorrow!');
INSERT INTO `quotes` VALUES ('If your life was a horse, you\'d have to shoot it.');
INSERT INTO `quotes` VALUES ('In the stairway of life, you\'d best take the elevator.');
INSERT INTO `quotes` VALUES ('Increased knowledge will help you now.  Have mate\'s phone bugged.');
INSERT INTO `quotes` VALUES ('Is that really YOU that is reading this?');
INSERT INTO `quotes` VALUES ('Is this really happening?');
INSERT INTO `quotes` VALUES ('It is so very hard to be an\non-your-own-take-care-of-yourself-because-there-is-no-one-else-to-do-it-for-you\ngrown-up.');
INSERT INTO `quotes` VALUES ('It may or may not be worthwhile, but it still has to be done.');
INSERT INTO `quotes` VALUES ('It was all so different before everything changed.');
INSERT INTO `quotes` VALUES ('It\'s a very *__UN*lucky week in which to be took dead.\n		-- Churchy La Femme');
INSERT INTO `quotes` VALUES ('It\'s all in the mind, ya know.');
INSERT INTO `quotes` VALUES ('It\'s lucky you\'re going so slowly, because you\'re going in the wrong direction.');
INSERT INTO `quotes` VALUES ('Just because the message may never be received does not mean it is\nnot worth sending.');
INSERT INTO `quotes` VALUES ('Just to have it is enough.');
INSERT INTO `quotes` VALUES ('Keep emotionally active.  Cater to your favorite neurosis.');
INSERT INTO `quotes` VALUES ('Keep it short for pithy sake.');
INSERT INTO `quotes` VALUES ('Lady Luck brings added income today.  Lady friend takes it away tonight.');
INSERT INTO `quotes` VALUES ('Learn to pause -- or nothing worthwhile can catch up to you.');
INSERT INTO `quotes` VALUES ('Let me put it this way: today is going to be a learning experience.');
INSERT INTO `quotes` VALUES ('Life is to you a dashing and bold adventure.');
INSERT INTO `quotes` VALUES ('\"Life, loathe it or ignore it, you can\'t like it.\"\n		-- Marvin, \"Hitchhiker\'s Guide to the Galaxy\"');
INSERT INTO `quotes` VALUES ('Live in a world of your own, but always welcome visitors.');
INSERT INTO `quotes` VALUES ('Living your life is a task so difficult, it has never been attempted before.');
INSERT INTO `quotes` VALUES ('Long life is in store for you.');
INSERT INTO `quotes` VALUES ('Look afar and see the end from the beginning.');
INSERT INTO `quotes` VALUES ('Love is in the offing.  Be affectionate to one who adores you.');
INSERT INTO `quotes` VALUES ('Make a wish, it might come true.');
INSERT INTO `quotes` VALUES ('Many changes of mind and mood; do not hesitate too long.');
INSERT INTO `quotes` VALUES ('Never be led astray onto the path of virtue.');
INSERT INTO `quotes` VALUES ('Never commit yourself!  Let someone else commit you.');
INSERT INTO `quotes` VALUES ('Never give an inch!');
INSERT INTO `quotes` VALUES ('Never look up when dragons fly overhead.');
INSERT INTO `quotes` VALUES ('Never reveal your best argument.');
INSERT INTO `quotes` VALUES ('Next Friday will not be your lucky day.  As a matter of fact, you don\'t\nhave a lucky day this year.');
INSERT INTO `quotes` VALUES ('Of course you have a purpose -- to find a purpose.');
INSERT INTO `quotes` VALUES ('People are beginning to notice you.  Try dressing before you leave the house.');
INSERT INTO `quotes` VALUES ('Perfect day for scrubbing the floor and other exciting things.');
INSERT INTO `quotes` VALUES ('Questionable day.\n\nAsk somebody something.');
INSERT INTO `quotes` VALUES ('Reply hazy, ask again later.');
INSERT INTO `quotes` VALUES ('Save energy: be apathetic.');
INSERT INTO `quotes` VALUES ('Ships are safe in harbor, but they were never meant to stay there.');
INSERT INTO `quotes` VALUES ('Slow day.  Practice crawling.');
INSERT INTO `quotes` VALUES ('Snow Day -- stay home.');
INSERT INTO `quotes` VALUES ('So this is it.  We\'re going to die.');
INSERT INTO `quotes` VALUES ('So you\'re back... about time...');
INSERT INTO `quotes` VALUES ('Someone is speaking well of you.');
INSERT INTO `quotes` VALUES ('Someone is speaking well of you.\n\nHow unusual!');
INSERT INTO `quotes` VALUES ('Someone whom you reject today, will reject you tomorrow.');
INSERT INTO `quotes` VALUES ('Stay away from flying saucers today.');
INSERT INTO `quotes` VALUES ('Stay away from hurricanes for a while.');
INSERT INTO `quotes` VALUES ('Stay the curse.');
INSERT INTO `quotes` VALUES ('That secret you\'ve been guarding, isn\'t.');
INSERT INTO `quotes` VALUES ('The time is right to make new friends.');
INSERT INTO `quotes` VALUES ('The whole world is a tuxedo and you are a pair of brown shoes.\n		-- George Gobel');
INSERT INTO `quotes` VALUES ('');
INSERT INTO `quotes` VALUES ('');
INSERT INTO `quotes` VALUES ('There is a fly on your nose.');
INSERT INTO `quotes` VALUES ('There was a phone call for you.');
INSERT INTO `quotes` VALUES ('There will be big changes for you but you will be happy.');
INSERT INTO `quotes` VALUES ('Things will be bright in P.M.  A cop will shine a light in your face.');
INSERT INTO `quotes` VALUES ('Think twice before speaking, but don\'t say \"think think click click\".');
INSERT INTO `quotes` VALUES ('This life is yours.  Some of it was given to you; the rest, you made yourself.');
INSERT INTO `quotes` VALUES ('This will be a memorable month -- no matter how hard you try to forget it.');
INSERT INTO `quotes` VALUES ('Time to be aggressive.  Go after a tattooed Virgo.');
INSERT INTO `quotes` VALUES ('Today is National Existential Ennui Awareness Day.');
INSERT INTO `quotes` VALUES ('Today is the first day of the rest of the mess.');
INSERT INTO `quotes` VALUES ('Today is the first day of the rest of your life.');
INSERT INTO `quotes` VALUES ('Today is the last day of your life so far.');
INSERT INTO `quotes` VALUES ('Today is the tomorrow you worried about yesterday.');
INSERT INTO `quotes` VALUES ('Today is what happened to yesterday.');
INSERT INTO `quotes` VALUES ('Today\'s weirdness is tomorrow\'s reason why.\n		-- Hunter S. Thompson');
INSERT INTO `quotes` VALUES ('Tomorrow will be cancelled due to lack of interest.');
INSERT INTO `quotes` VALUES ('Tomorrow, this will be part of the unchangeable past but fortunately,\nit can still be changed today.');
INSERT INTO `quotes` VALUES ('Tomorrow, you can be anywhere.');
INSERT INTO `quotes` VALUES ('Tonight you will pay the wages of sin; Don\'t forget to leave a tip.');
INSERT INTO `quotes` VALUES ('Tonight\'s the night: Sleep in a eucalyptus tree.');
INSERT INTO `quotes` VALUES ('Troubled day for virgins over 16 who are beautiful and wealthy and live\nin eucalyptus trees.');
INSERT INTO `quotes` VALUES ('Truth will out this morning.  (Which may really mess things up.)');
INSERT INTO `quotes` VALUES ('Try the Moo Shu Pork.  It is especially good today.');
INSERT INTO `quotes` VALUES ('Try to get all of your posthumous medals in advance.');
INSERT INTO `quotes` VALUES ('Try to have as good a life as you can under the circumstances.');
INSERT INTO `quotes` VALUES ('Try to relax and enjoy the crisis.\n		-- Ashleigh Brilliant');
INSERT INTO `quotes` VALUES ('Try to value useful qualities in one who loves you.');
INSERT INTO `quotes` VALUES ('Tuesday After Lunch is the cosmic time of the week.');
INSERT INTO `quotes` VALUES ('Tuesday is the Wednesday of the rest of your life.');
INSERT INTO `quotes` VALUES ('What happened last night can happen again.');
INSERT INTO `quotes` VALUES ('While you recently had your problems on the run, they\'ve regrouped and\nare making another attack.');
INSERT INTO `quotes` VALUES ('Write yourself a threatening letter and pen a defiant reply.');
INSERT INTO `quotes` VALUES ('You are a bundle of energy, always on the go.');
INSERT INTO `quotes` VALUES ('You are a fluke of the universe; you have no right to be here.');
INSERT INTO `quotes` VALUES ('You are a very redundant person, that\'s what kind of person you are.');
INSERT INTO `quotes` VALUES ('You are always busy.');
INSERT INTO `quotes` VALUES ('You are as I am with You.');
INSERT INTO `quotes` VALUES ('You are capable of planning your future.');
INSERT INTO `quotes` VALUES ('You are confused; but this is your normal state.');
INSERT INTO `quotes` VALUES ('You are deeply attached to your friends and acquaintances.');
INSERT INTO `quotes` VALUES ('You are destined to become the commandant of the fighting men of the\ndepartment of transportation.');
INSERT INTO `quotes` VALUES ('You are dishonest, but never to the point of hurting a friend.');
INSERT INTO `quotes` VALUES ('You are fairminded, just and loving.');
INSERT INTO `quotes` VALUES ('You are farsighted, a good planner, an ardent lover, and a faithful friend.');
INSERT INTO `quotes` VALUES ('You are fighting for survival in your own sweet and gentle way.');
INSERT INTO `quotes` VALUES ('You are going to have a new love affair.');
INSERT INTO `quotes` VALUES ('You are magnetic in your bearing.');
INSERT INTO `quotes` VALUES ('You are not dead yet.  But watch for further reports.');
INSERT INTO `quotes` VALUES ('You are number 6!  Who is number one?');
INSERT INTO `quotes` VALUES ('You are only young once, but you can stay immature indefinitely.');
INSERT INTO `quotes` VALUES ('You are scrupulously honest, frank, and straightforward.  Therefore you\nhave few friends.');
INSERT INTO `quotes` VALUES ('You are sick, twisted and perverted.  I like that in a person.');
INSERT INTO `quotes` VALUES ('You are so boring that when I see you my feet go to sleep.');
INSERT INTO `quotes` VALUES ('You are standing on my toes.');
INSERT INTO `quotes` VALUES ('You are taking yourself far too seriously.');
INSERT INTO `quotes` VALUES ('You are the only person to ever get this message.');
INSERT INTO `quotes` VALUES ('You are wise, witty, and wonderful, but you spend too much time reading\nthis sort of trash.');
INSERT INTO `quotes` VALUES ('You attempt things that you do not even plan because of your extreme stupidity.');
INSERT INTO `quotes` VALUES ('You can create your own opportunities this week.  Blackmail a senior executive.');
INSERT INTO `quotes` VALUES ('You can do very well in speculation where land or anything to do with dirt\nis concerned.');
INSERT INTO `quotes` VALUES ('You can rent this space for only $5 a week.');
INSERT INTO `quotes` VALUES ('You could live a better life, if you had a better mind and a better body.');
INSERT INTO `quotes` VALUES ('You definitely intend to start living sometime soon.');
INSERT INTO `quotes` VALUES ('You dialed 5483.');
INSERT INTO `quotes` VALUES ('You display the wonderful traits of charm and courtesy.');
INSERT INTO `quotes` VALUES ('You don\'t become a failure until you\'re satisfied with being one.');
INSERT INTO `quotes` VALUES ('You enjoy the company of other people.');
INSERT INTO `quotes` VALUES ('You feel a whole lot more like you do now than you did when you used to.');
INSERT INTO `quotes` VALUES ('You fill a much-needed gap.');
INSERT INTO `quotes` VALUES ('You get along very well with everyone except animals and people.');
INSERT INTO `quotes` VALUES ('You had some happiness once, but your parents moved away, and you had to\nleave it behind.');
INSERT INTO `quotes` VALUES ('You have a deep appreciation of the arts and music.');
INSERT INTO `quotes` VALUES ('You have a deep interest in all that is artistic.');
INSERT INTO `quotes` VALUES ('You have a reputation for being thoroughly reliable and trustworthy.\nA pity that it\'s totally undeserved.');
INSERT INTO `quotes` VALUES ('You have a strong appeal for members of the opposite sex.');
INSERT INTO `quotes` VALUES ('You have a strong appeal for members of your own sex.');
INSERT INTO `quotes` VALUES ('You have a strong desire for a home and your family interests come first.');
INSERT INTO `quotes` VALUES ('You have a truly strong individuality.');
INSERT INTO `quotes` VALUES ('You have a will that can be influenced by all with whom you come in contact.');
INSERT INTO `quotes` VALUES ('You have an ability to sense and know higher truth.');
INSERT INTO `quotes` VALUES ('You have an ambitious nature and may make a name for yourself.');
INSERT INTO `quotes` VALUES ('You have an unusual equipment for success.  Be sure to use it properly.');
INSERT INTO `quotes` VALUES ('You have an unusual magnetic personality.  Don\'t walk too close to\nmetal objects which are not fastened down.');
INSERT INTO `quotes` VALUES ('You have an unusual understanding of the problems of human relationships.');
INSERT INTO `quotes` VALUES ('You have been selected for a secret mission.');
INSERT INTO `quotes` VALUES ('You have Egyptian flu: you\'re going to be a mummy.');
INSERT INTO `quotes` VALUES ('You have had a long-term stimulation relative to business.');
INSERT INTO `quotes` VALUES ('You have literary talent that you should take pains to develop.');
INSERT INTO `quotes` VALUES ('You have many friends and very few living enemies.');
INSERT INTO `quotes` VALUES ('You have no real enemies.');
INSERT INTO `quotes` VALUES ('You have taken yourself too seriously.');
INSERT INTO `quotes` VALUES ('You have the body of a 19 year old.  Please return it before it gets wrinkled.');
INSERT INTO `quotes` VALUES ('You have the capacity to learn from mistakes.  You\'ll learn a lot today.');
INSERT INTO `quotes` VALUES ('You have the power to influence all with whom you come in contact.');
INSERT INTO `quotes` VALUES ('You learn to write as if to someone else because NEXT YEAR YOU WILL BE\n\"SOMEONE ELSE.\"');
INSERT INTO `quotes` VALUES ('You like to form new friendships and make new acquaintances.');
INSERT INTO `quotes` VALUES ('You look like a million dollars.  All green and wrinkled.');
INSERT INTO `quotes` VALUES ('You look tired.');
INSERT INTO `quotes` VALUES ('You love peace.');
INSERT INTO `quotes` VALUES ('You love your home and want it to be beautiful.');
INSERT INTO `quotes` VALUES ('You may be gone tomorrow, but that doesn\'t mean that you weren\'t here today.');
INSERT INTO `quotes` VALUES ('You may be infinitely smaller than some things, but you\'re infinitely\nlarger than others.');
INSERT INTO `quotes` VALUES ('You may be recognized soon.  Hide.');
INSERT INTO `quotes` VALUES ('You may get an opportunity for advancement today.  Watch it!');
INSERT INTO `quotes` VALUES ('You may worry about your hair-do today, but tomorrow much peanut butter will\nbe sold.');
INSERT INTO `quotes` VALUES ('You need more time; and you probably always will.');
INSERT INTO `quotes` VALUES ('You need no longer worry about the future.  This time tomorrow you\'ll be dead.');
INSERT INTO `quotes` VALUES ('You never hesitate to tackle the most difficult problems.');
INSERT INTO `quotes` VALUES ('You never know how many friends you have until you rent a house on the beach.');
INSERT INTO `quotes` VALUES ('You now have Asian Flu.');
INSERT INTO `quotes` VALUES ('You own a dog, but you can only feed a cat.');
INSERT INTO `quotes` VALUES ('You plan things that you do not even attempt because of your extreme caution.');
INSERT INTO `quotes` VALUES ('You possess a mind not merely twisted, but actually sprained.');
INSERT INTO `quotes` VALUES ('You prefer the company of the opposite sex, but are well liked by your own.');
INSERT INTO `quotes` VALUES ('You recoil from the crude; you tend naturally toward the exquisite.');
INSERT INTO `quotes` VALUES ('You seek to shield those you love and you like the role of the provider.');
INSERT INTO `quotes` VALUES ('You shall be rewarded for a dastardly deed.');
INSERT INTO `quotes` VALUES ('You should emulate your heros, but don\'t carry it too far.  Especially\nif they are dead.');
INSERT INTO `quotes` VALUES ('You should go home.');
INSERT INTO `quotes` VALUES ('You single-handedly fought your way into this hopeless mess.');
INSERT INTO `quotes` VALUES ('You teach best what you most need to learn.');
INSERT INTO `quotes` VALUES ('You too can wear a nose mitten.');
INSERT INTO `quotes` VALUES ('You two ought to be more careful--your love could drag on for years and years.');
INSERT INTO `quotes` VALUES ('You will always get the greatest recognition for the job you least like.');
INSERT INTO `quotes` VALUES ('You will always have good luck in your personal affairs.');
INSERT INTO `quotes` VALUES ('You will attract cultured and artistic people to your home.');
INSERT INTO `quotes` VALUES ('You will be a winner today.  Pick a fight with a four-year-old.');
INSERT INTO `quotes` VALUES ('You will be advanced socially, without any special effort on your part.');
INSERT INTO `quotes` VALUES ('You will be aided greatly by a person whom you thought to be unimportant.');
INSERT INTO `quotes` VALUES ('You will be attacked by a beast who has the body of a wolf, the tail of\na lion, and the face of Donald Duck.');
INSERT INTO `quotes` VALUES ('You will be audited by the Internal Revenue Service.');
INSERT INTO `quotes` VALUES ('You will be awarded a medal for disregarding safety in saving someone.');
INSERT INTO `quotes` VALUES ('You will be awarded some great honor.');
INSERT INTO `quotes` VALUES ('You will be awarded the Nobel Peace Prize... posthumously.');
INSERT INTO `quotes` VALUES ('You will be called upon to help a friend in trouble.');
INSERT INTO `quotes` VALUES ('You will be divorced within a year.');
INSERT INTO `quotes` VALUES ('You will be given a post of trust and responsibility.');
INSERT INTO `quotes` VALUES ('You will be held hostage by a radical group.');
INSERT INTO `quotes` VALUES ('You will be honored for contributing your time and skill to a worthy cause.');
INSERT INTO `quotes` VALUES ('You will be imprisoned for contributing your time and skill to a bank robbery.');
INSERT INTO `quotes` VALUES ('You will be married within a year, and divorced within two.');
INSERT INTO `quotes` VALUES ('You will be married within a year.');
INSERT INTO `quotes` VALUES ('You will be misunderstood by everyone.');
INSERT INTO `quotes` VALUES ('You will be recognized and honored as a community leader.');
INSERT INTO `quotes` VALUES ('You will be reincarnated as a toad; and you will be much happier.');
INSERT INTO `quotes` VALUES ('You will be run over by a beer truck.');
INSERT INTO `quotes` VALUES ('You will be run over by a bus.');
INSERT INTO `quotes` VALUES ('You will be singled out for promotion in your work.');
INSERT INTO `quotes` VALUES ('You will be successful in love.');
INSERT INTO `quotes` VALUES ('You will be surprised by a loud noise.');
INSERT INTO `quotes` VALUES ('You will be surrounded by luxury.');
INSERT INTO `quotes` VALUES ('You will be the last person to buy a Chrysler.');
INSERT INTO `quotes` VALUES ('You will be the victim of a bizarre joke.');
INSERT INTO `quotes` VALUES ('You will be Told about it Tomorrow.  Go Home and Prepare Thyself.');
INSERT INTO `quotes` VALUES ('You will be traveling and coming into a fortune.');
INSERT INTO `quotes` VALUES ('You will be winged by an anti-aircraft battery.');
INSERT INTO `quotes` VALUES ('You will become rich and famous unless you don\'t.');
INSERT INTO `quotes` VALUES ('You will contract a rare disease.');
INSERT INTO `quotes` VALUES ('You will engage in a profitable business activity.');
INSERT INTO `quotes` VALUES ('You will experience a strong urge to do good; but it will pass.');
INSERT INTO `quotes` VALUES ('You will feel hungry again in another hour.');
INSERT INTO `quotes` VALUES ('You will forget that you ever knew me.');
INSERT INTO `quotes` VALUES ('You will gain money by a fattening action.');
INSERT INTO `quotes` VALUES ('You will gain money by a speculation or lottery.');
INSERT INTO `quotes` VALUES ('You will gain money by an illegal action.');
INSERT INTO `quotes` VALUES ('You will gain money by an immoral action.');
INSERT INTO `quotes` VALUES ('You will get what you deserve.');
INSERT INTO `quotes` VALUES ('You will give someone a piece of your mind, which you can ill afford.');
INSERT INTO `quotes` VALUES ('You will have a long and boring life.');
INSERT INTO `quotes` VALUES ('You will have a long and unpleasant discussion with your supervisor.');
INSERT INTO `quotes` VALUES ('You will have domestic happiness and faithful friends.');
INSERT INTO `quotes` VALUES ('You will have good luck and overcome many hardships.');
INSERT INTO `quotes` VALUES ('You will have long and healthy life.');
INSERT INTO `quotes` VALUES ('You will hear good news from one you thought unfriendly to you.');
INSERT INTO `quotes` VALUES ('You will inherit millions of dollars.');
INSERT INTO `quotes` VALUES ('You will inherit some money or a small piece of land.');
INSERT INTO `quotes` VALUES ('You will live a long, healthy, happy life and make bags of money.');
INSERT INTO `quotes` VALUES ('You will live to see your grandchildren.');
INSERT INTO `quotes` VALUES ('You will lose your present job and have to become a door to door mayonnaise\nsalesman.');
INSERT INTO `quotes` VALUES ('You will meet an important person who will help you advance professionally.');
INSERT INTO `quotes` VALUES ('You will never know hunger.');
INSERT INTO `quotes` VALUES ('You will not be elected to public office this year.');
INSERT INTO `quotes` VALUES ('You will obey or molten silver will be poured into your ears.');
INSERT INTO `quotes` VALUES ('You will outgrow your usefulness.');
INSERT INTO `quotes` VALUES ('You will overcome the attacks of jealous associates.');
INSERT INTO `quotes` VALUES ('You will pass away very quickly.');
INSERT INTO `quotes` VALUES ('You will pay for your sins.  If you have already paid, please disregard\nthis message.');
INSERT INTO `quotes` VALUES ('You will pioneer the first Martian colony.');
INSERT INTO `quotes` VALUES ('You will probably marry after a very brief courtship.');
INSERT INTO `quotes` VALUES ('You will reach the highest possible point in your business or profession.');
INSERT INTO `quotes` VALUES ('You will receive a legacy which will place you above want.');
INSERT INTO `quotes` VALUES ('You will remember something that you should not have forgotten.');
INSERT INTO `quotes` VALUES ('You will soon forget this.');
INSERT INTO `quotes` VALUES ('You will soon meet a person who will play an important role in your life.');
INSERT INTO `quotes` VALUES ('You will step on the night soil of many countries.');
INSERT INTO `quotes` VALUES ('You will stop at nothing to reach your objective, but only because your\nbrakes are defective.');
INSERT INTO `quotes` VALUES ('You will triumph over your enemy.');
INSERT INTO `quotes` VALUES ('You will visit the Dung Pits of Glive soon.');
INSERT INTO `quotes` VALUES ('You will win success in whatever calling you adopt.');
INSERT INTO `quotes` VALUES ('You will wish you hadn\'t.');
INSERT INTO `quotes` VALUES ('You work very hard.  Don\'t try to think as well.');
INSERT INTO `quotes` VALUES ('You worry too much about your job.  Stop it.  You are not paid enough to worry.');
INSERT INTO `quotes` VALUES ('You would if you could but you can\'t so you won\'t.');
INSERT INTO `quotes` VALUES ('You\'d like to do it instantaneously, but that\'s too slow.');
INSERT INTO `quotes` VALUES ('You\'ll be called to a post requiring ability in handling groups of people.');
INSERT INTO `quotes` VALUES ('You\'ll be sorry...');
INSERT INTO `quotes` VALUES ('You\'ll feel devilish tonight.  Toss dynamite caps under a flamenco dancer\'s\nheel.');
INSERT INTO `quotes` VALUES ('You\'ll feel much better once you\'ve given up hope.');
INSERT INTO `quotes` VALUES ('You\'ll never be the man your mother was!');
INSERT INTO `quotes` VALUES ('You\'ll never see all the places, or read all the books, but fortunately,\nthey\'re not all recommended.');
INSERT INTO `quotes` VALUES ('You\'ll wish that you had done some of the hard things when they were easier\nto do.');
INSERT INTO `quotes` VALUES ('You\'re a card which will have to be dealt with.');
INSERT INTO `quotes` VALUES ('You\'re almost as happy as you think you are.');
INSERT INTO `quotes` VALUES ('You\'re at the end of the road again.');
INSERT INTO `quotes` VALUES ('You\'re being followed.  Cut out the hanky-panky for a few days.');
INSERT INTO `quotes` VALUES ('You\'re currently going through a difficult transition period called \"Life.\"');
INSERT INTO `quotes` VALUES ('You\'re definitely on their list.  The question to ask next is what list it is.');
INSERT INTO `quotes` VALUES ('You\'re growing out of some of your problems, but there are others that\nyou\'re growing into.');
INSERT INTO `quotes` VALUES ('You\'re not my type.  For that matter, you\'re not even my species!!!');
INSERT INTO `quotes` VALUES ('You\'re ugly and your mother dresses you funny.');
INSERT INTO `quotes` VALUES ('You\'re working under a slight handicap.  You happen to be human.');
INSERT INTO `quotes` VALUES ('You\'ve been leading a dog\'s life.  Stay off the furniture.');
INSERT INTO `quotes` VALUES ('Your aim is high and to the right.');
INSERT INTO `quotes` VALUES ('Your aims are high, and you are capable of much.');
INSERT INTO `quotes` VALUES ('Your analyst has you mixed up with another patient.  Don\'t believe a\nthing he tells you.');
INSERT INTO `quotes` VALUES ('Your best consolation is the hope that the things you failed to get weren\'t\nreally worth having.');
INSERT INTO `quotes` VALUES ('Your boss climbed the corporate ladder, wrong by wrong.');
INSERT INTO `quotes` VALUES ('Your boss is a few sandwiches short of a picnic.');
INSERT INTO `quotes` VALUES ('Your boyfriend takes chocolate from strangers.');
INSERT INTO `quotes` VALUES ('Your business will assume vast proportions.');
INSERT INTO `quotes` VALUES ('Your business will go through a period of considerable expansion.');
INSERT INTO `quotes` VALUES ('Your depth of comprehension may tend to make you lax in worldly ways.');
INSERT INTO `quotes` VALUES ('Your domestic life may be harmonious.');
INSERT INTO `quotes` VALUES ('Your fly might be open (but don\'t check it just now).');
INSERT INTO `quotes` VALUES ('Your goose is cooked.\n(Your current chick is burned up too!)');
INSERT INTO `quotes` VALUES ('Your heart is pure, and your mind clear, and your soul devout.');
INSERT INTO `quotes` VALUES ('Your ignorance cramps my conversation.');
INSERT INTO `quotes` VALUES ('Your life would be very empty if you had nothing to regret.');
INSERT INTO `quotes` VALUES ('Your love life will be happy and harmonious.');
INSERT INTO `quotes` VALUES ('Your love life will be... interesting.');
INSERT INTO `quotes` VALUES ('Your lover will never wish to leave you.');
INSERT INTO `quotes` VALUES ('Your lucky color has faded.');
INSERT INTO `quotes` VALUES ('Your lucky number has been disconnected.');
INSERT INTO `quotes` VALUES ('Your lucky number is 3552664958674928.  Watch for it everywhere.');
INSERT INTO `quotes` VALUES ('Your mode of life will be changed for the better because of good news soon.');
INSERT INTO `quotes` VALUES ('Your mode of life will be changed for the better because of new developments.');
INSERT INTO `quotes` VALUES ('Your motives for doing whatever good deed you may have in mind will be\nmisinterpreted by somebody.');
INSERT INTO `quotes` VALUES ('Your nature demands love and your happiness depends on it.');
INSERT INTO `quotes` VALUES ('Your object is to save the world, while still leading a pleasant life.');
INSERT INTO `quotes` VALUES ('Your own qualities will help prevent your advancement in the world.');
INSERT INTO `quotes` VALUES ('Your present plans will be successful.');
INSERT INTO `quotes` VALUES ('Your reasoning is excellent -- it\'s only your basic assumptions that are wrong.');
INSERT INTO `quotes` VALUES ('Your reasoning powers are good, and you are a fairly good planner.');
INSERT INTO `quotes` VALUES ('Your sister swims out to meet troop ships.');
INSERT INTO `quotes` VALUES ('Your society will be sought by people of taste and refinement.');
INSERT INTO `quotes` VALUES ('Your step will soil many countries.');
INSERT INTO `quotes` VALUES ('Your supervisor is thinking about you.');
INSERT INTO `quotes` VALUES ('Your talents will be recognized and suitably rewarded.');
INSERT INTO `quotes` VALUES ('Your temporary financial embarrassment will be relieved in a surprising manner.');
INSERT INTO `quotes` VALUES ('Your true value depends entirely on what you are compared with.');
/*!40000 ALTER TABLE `quotes` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
