apiVersion: v1
kind: Service
metadata:
  name: fortune
  labels:
    name: fortune
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: fortune
